#!/bin/sh
echo "root:Openwrt_1234567" | chpasswd

# ===wan (eth0) dhcp--pppoe
uci set network.wan.proto='pppoe'
uci set network.wan.username='18052040667'
uci set network.wan.password='09223147'
uci commit network

# ===wifi
uci set wireless.radio0.disabled='0'
uci set wireless.radio0.band='2g'
uci set wireless.radio0.channel='1'
uci set wireless.radio0.htmode='HT20'
uci set wireless.radio0.country='CN'
# uci set wireless.radio0.txpower='20'
uci set wireless.radio0.cell_density='1'
uci set wireless.default_radio0.device='radio0'
uci set wireless.default_radio0.network='lan'
uci set wireless.default_radio0.mode='ap'
uci set wireless.default_radio0.ssid='Immortalwrt-2'
uci set wireless.default_radio0.encryption='psk2+ccmp'
uci set wireless.default_radio0.key='Sui123456'

# uci set wireless.management_wifi=wifi-iface
uci set wireless.management_wifi.device='radio0'
uci set wireless.management_wifi.network='lan'
uci set wireless.management_wifi.mode='ap'
uci set wireless.management_wifi.ssid='PandoraBox-2.4G'
uci set wireless.management_wifi.encryption='psk2'
uci set wireless.management_wifi.key='Sui123456'

uci set wireless.radio1.disabled='0'
uci set wireless.radio0.band='5g'
uci set wireless.radio1.channel='36'
uci set wireless.radio1.htmode='VHT80'
uci set wireless.radio1.country='CN'
# uci set wireless.radio1.txpower='20'
uci set wireless.radio1.cell_density='1'
uci set wireless.default_radio1.ssid='PandoraBox-5G'
uci set wireless.default_radio1.encryption='psk2+ccmp'
uci set wireless.default_radio1.key='Sui123456'

uci commit wireless
/etc/init.d/network reload
rm -f /etc/uci-defaults/99-initialize
