#!/bin/sh
echo "root:Openwrt_1234567" | chpasswd

# ===wan (eth0) dhcp--pppoe
uci set network.wan.proto='pppoe'
uci set network.wan.username='18052040667'
uci set network.wan.password='09223147'
uci set network.wan.device='wan.11'
# uci set network.wan.mtu='1492'
uci set network.wan6.proto='dhcpv6'
uci set network.wan6.device='wan.11'
uci commit network

# ===wifi
uci set wireless.radio0.disabled='0'
uci set wireless.radio0.country='CN'
uci set wireless.radio0.channel='1'
uci set wireless.radio0.htmode='HT20'
# uci set wireless.radio0.txpower='20'
uci set wireless.default_radio0.ssid='Pandorabox-2.4G'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='Sui123456'
uci set wireless.default_radio0.disabled='0'

uci add wireless wifi-iface
uci set wireless.@wifi-iface[-1].device='radio0'
uci set wireless.@wifi-iface[-1].network='lan'
uci set wireless.@wifi-iface[-1].mode='ap'
uci set wireless.@wifi-iface[-1].ssid='Immortalwrt-2.4G-2'
uci set wireless.@wifi-iface[-1].hidden='0'
uci set wireless.@wifi-iface[-1].encryption='psk2'
uci set wireless.@wifi-iface[-1].key='Sui123456'
uci set wireless.@wifi-iface[-1].disabled='0'

uci set wireless.radio1.disabled='0'
uci set wireless.radio1.country='CN'
uci set wireless.radio1.channel='36'
uci set wireless.radio1.htmode='VHT80'
# uci set wireless.radio1.txpower='20'
uci set wireless.default_radio1.ssid='Pandorabox-5G'
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key='Sui123456'
uci set wireless.default_radio1.disabled='0'

uci commit wireless
/etc/init.d/network reload
rm -f /etc/uci-defaults/99-initialize
